apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nginx
  annotations: {{ .Values.service.annotations | toYaml | nindent 2 }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
